### PR TITLE
Update Clikt dependency from 3.2.0 to 4.2.0

### PR DESCRIPTION
**Pull request by Lax125**
# Description

See title. We are doing this as a part of a larger task to build a CLI tool for HC/EWB.

# Associated tasks:

Tasks blocking this one:
- None

Tasks this is blocking:
- None

# Checklist:

These are always required, if you do not do them, reviewers will be angry:
- [x] I have performed a self review of my own code.
- [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary. (No tests needed for dependency bump)

These you can remove from the list if they are not applicable for this PR.
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have considered if this is a breaking change and have communicated it with other team members if so. (Not breaking)

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [EWB-4023 Update Clikt to 4.2.0 in evolve-super-pom](https://app.clickup.com/t/6929263/EWB-4023)

**Review by kgreav — CHANGES_REQUESTED** [review]
You've gotta update the super pom version.

**Comment by Lax125** [comment]
tru tru

**Comment by kgreav** [comment]
oh lol that was literally a minute ago... sorry must have just checked my emails right after you created this.

**Comment by Lax125** [comment]
PR any% speedrun

**Review by kgreav — APPROVED** [review]

**Comment by kgreav** [comment]
> PR any% speedrun

think i failed the speedrun... :facepalm:

**Pull request merged**
