### PR TITLE
EWB-4086: Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by Lax125**
# Description

Update dependencies with registered vulnerabilities (CVE) to the latest non-beta version.

# Associated tasks

Tasks blocking this one:
- None

Tasks this is blocking:
- None

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [ ] ~I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ (No tests needed for super pom update. Tests in repos using this super pom will be updated if needed in the future.)
- [ ] ~I have commented my code in any hard-to-understand or hacky areas.~
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).
      
### Documentation
- [x] I have updated the changelog.
- [ ] ~I have updated any documentation required for these changes.~

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

Two packages have group ID changes due to being moved in maven central: unirest-java (com.mashape.unirest ➝ com.konghq), dom4j (dom4j ➝ com.dom4j).

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [EWB-4086 Update vulnerable dependencies in super pom](https://app.clickup.com/t/6929263/EWB-4086)

**Comment by Lax125** [comment]
Do we not have a changelog for the super pom? It would be helpful as a reference of the breaking changes when updating child projects.

**Comment by kgreav** [comment]
> Do we not have a changelog for the super pom? It would be helpful as a reference of the breaking changes when updating child projects.

We do not. I agree, please add one.

**Comment by Lax125** [comment]
We could modernise the github workflows too (`release` action that increments version and prepares changelog for next version)

**Comment by Lax125** [comment]
Although that could be left for a future PR

**Review by kgreav — APPROVED** [review]

**Comment by kgreav** [comment]
Yep thanks, i'll raise it with Alex to have a look at after he's done with docs.

**Pull request merged**
